name: Deploy to Demo
run-name: Deployment to demo by ${{ github.actor }}
on: [push]
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Starting job started by ${{ github.event_name }} event."
      - run: echo "Running ${{ runner.os }}."
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{secrets.SSH_CONFIG}}" > ~/.ssh/config
          cat ~/.ssh/config
          echo "${{secrets.SSH_KEY}}" > ~/.ssh/demo.key
          chmod 600 ~/.ssh/demo.key
      - name: Checkout
        run: |
          ssh demo 'cd ~/services/uuriv-oppija/ && git fetch && git reset --hard origin/main && sudo chmod +x ./update-to-nginx.sh'
      - name: Build & deploy
        run: |
          ssh demo 'cd ~/services/uuriv-oppija && sudo ./update-to-nginx.sh'
          sleep 10
      - name: Clean up
        run: |
          exit
          sudo rm -rf ~/.ssh/
